version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    restart: always
    volumes:
      - ./upstream/:/etc/nginx/conf.d/
      - /opt/ssl/nginx:/opt/ssl/nginx
    ports:
      - 80:80
      - 443:443
  mysql:
    container_name: mysql
    image: mysql:8.0.28-oracle
    restart: always
    ports:
      - 6033:3306
    environment:
      - MYSQL_ROOT_PASSWORD=5c2891d9-45fb-4240-9f0e-50222099d9bd
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin