version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    restart: always
    volumes:
      - ./upstream/:/etc/nginx/conf.d/
      - /opt/ssl/nginx/:/opt/ssl/nginx/
    ports:
      - 80:80
      - 443:443